--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-08-23 09:20:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16509)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "IsIncome" boolean NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16508)
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16525)
-- Name: Transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transactions" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Amount" numeric NOT NULL,
    "Comment" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."Transactions" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16524)
-- Name: Transactions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Transactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16517)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "LastName" text NOT NULL,
    "Patronymic" text,
    "Username" text NOT NULL,
    "Password" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16516)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16503)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4805 (class 0 OID 16509)
-- Dependencies: 217
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name", "IsIncome") FROM stdin;
1	Заработная плата	t
2	Аренда недвижимости	t
3	Иные расходы	t
4	Продукты питания	f
5	Транспорт	f
6	Мобильная связь	f
7	Интернет	f
8	Развлечения	f
9	Другое	f
\.


--
-- TOC entry 4809 (class 0 OID 16525)
-- Dependencies: 221
-- Data for Name: Transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Transactions" ("Id", "Date", "Amount", "Comment", "CategoryId", "UserId") FROM stdin;
1	2024-08-16 21:46:48+03	12312	asda	2	1
2	2024-08-16 22:09:34+03	20000	asdasd	2	1
3	2024-08-16 22:26:09+03	10000	Машина	5	1
4	2024-08-16 22:40:17+03	10000	Иноые расходы	3	1
5	2024-08-19 21:14:41+03	20000	автомобиль	5	1
6	2024-08-20 09:12:27+03	5555	hgkjhg	1	1
7	2024-08-21 19:04:20+03	1000	интернет	7	1
8	2024-08-23 09:10:52+03	25000	аренда квартиры	2	1
9	2024-08-23 09:10:52+03	12000	аренда квартиры	2	1
\.


--
-- TOC entry 4807 (class 0 OID 16517)
-- Dependencies: 219
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "LastName", "Patronymic", "Username", "Password") FROM stdin;
1	1\n	1	1	1	1
2	Алексей	Сергеев	Валентинович	admin	admin
3	Иван	Иванов	Иванович	user1	user1
4	Иван	Носов	Андреевич	user1	user1
\.


--
-- TOC entry 4803 (class 0 OID 16503)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240816182106_Initial	8.0.7
\.


--
-- TOC entry 4815 (class 0 OID 0)
-- Dependencies: 216
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 9, true);


--
-- TOC entry 4816 (class 0 OID 0)
-- Dependencies: 220
-- Name: Transactions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Transactions_Id_seq"', 9, true);


--
-- TOC entry 4817 (class 0 OID 0)
-- Dependencies: 218
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 4, true);


--
-- TOC entry 4651 (class 2606 OID 16515)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- TOC entry 4657 (class 2606 OID 16531)
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id");


--
-- TOC entry 4653 (class 2606 OID 16523)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4649 (class 2606 OID 16507)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4654 (class 1259 OID 16542)
-- Name: IX_Transactions_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_CategoryId" ON public."Transactions" USING btree ("CategoryId");


--
-- TOC entry 4655 (class 1259 OID 16543)
-- Name: IX_Transactions_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transactions_UserId" ON public."Transactions" USING btree ("UserId");


--
-- TOC entry 4658 (class 2606 OID 16532)
-- Name: Transactions FK_Transactions_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- TOC entry 4659 (class 2606 OID 16537)
-- Name: Transactions FK_Transactions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2024-08-23 09:20:31

--
-- PostgreSQL database dump complete
--

